spring:
  servlet:
    multipart:
      max-request-size: 200MB
      max-file-size: 200MB
    jmx:
      unique-names: true
  main:
    allow-bean-definition-overriding: true
  application:
    name: SoundMentor-web
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.148.229.137:3306/sound_mentor
    username: root
    password: 123456
  redis:
    host: 8.148.229.137
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 8
  mail:
    host: smtp.163.com
    username: fzw1938@163.com
    password: EWiPDkat4FXdtuh5
    port: 465
    protocol: smtp
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
  # 配置 rabbitMq 服务器
  rabbitmq:
    host: 8.148.229.137
    port: 5672
    username: admin
    password: 123456
    template:
      retry:
        enabled: true # 开启生产者重试
        initial-interval: 1000ms # 初始重试间隔
        multiplier: 2 # 每次重试间隔的乘数
        max-attempts: 3 # 最大重试次数
        max-interval: 10000ms # 最大重试间隔
    listener:
      simple:
        retry:
          enabled: true # 开启消费者重试
          initial-interval: 1000ms # 初始重试间隔
          multiplier: 2 # 每次重试间隔的乘数
          max-attempts: 3 # 最大重试次数
          max-interval: 10000ms # 最大重试间隔
        recovery:
          enabled: true # 开启消费者重试失败后的恢复策略

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


organization:
  # 创建组织时默认最大用户容量
  defaultOrganizationCapacity: 999
  # 用户最多加入组织数量
  MaxOrganizations: 10

user:
  # 用户最大声音样本库数量限制
  maxSound: 100

minio:
  url: http://8.148.229.137:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket:
    img: img
    mp3: mp3
    doc: doc
    ppt: ppt
