spring:
  servlet:
    multipart:
      max-request-size: 200MB
      max-file-size: 200MB
    jmx:
      unique-names: true
  main:
    allow-bean-definition-overriding: true
  application:
    name: SoundMentor-web
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.43.62.36:3306/sound_mentor
    username: root
    password: 123456
  redis:
    host: 121.43.62.36
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 8

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
