spring:
  servlet:
    multipart:
      max-request-size: 200MB
      max-file-size: 200MB
    jmx:
      unique-names: true
  main:
    allow-bean-definition-overriding: true
  application:
    name: SoundMentor-web
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.43.62.36:3306/sound_mentor
    username: root
    password: 123456
  redis:
    host: 121.43.62.36
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 8
  mail:
    host: smtp.163.com
    username: fzw1938@163.com
    password: EWiPDkat4FXdtuh5
    port: 465
    protocol: smtp
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


organization:
  # 创建组织时默认最大用户容量
  defaultOrganizationCapacity: 999
  # 用户最多加入组织数量
  MaxOrganizations: 10

minio:
  url: http://121.43.62.36:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket:
    img: img
    mp3: mp3
    doc: doc
    ppt: ppt
